#!/usr/bin/env python
import argparse
import logging
import os

from ricecooker.chefs import LineCook
from ricecooker.config import LOGGER


# LOGGING SETTINGS
################################################################################
logging.getLogger("cachecontrol.controller").setLevel(logging.WARNING)
logging.getLogger("requests.packages").setLevel(logging.WARNING)
LOGGER.setLevel(logging.DEBUG)



# OPEN STAX LINE COOK
################################################################################

class OpenStaxChef(LineCook):
    """
    Sushi chef for uploading the OpenStax content folders generated by `souschef.py`.
    """

    def __init__(self, *args, **kwargs):
        """
        This subclass needs to have implement an `__init__` method for the argparse
        logic to work correctly since we want to mixing command line args from:
        `BaseChef`, `SushiChef`, `JsonTreeChef`, and `LineCook`.
        """
        super(OpenStaxChef, self).__init__(*args, **kwargs)


# CLI
################################################################################

if __name__ == '__main__':
    chef = OpenStaxChef()
    chef.main()

