mime = {
"Application/xml": ['.filters', '.vcproj', '.vcxproj'],
"application/PowerShell": ['.psc1'],
"application/atom+xml": ['.atom'],
"application/directx": ['.x'],
"application/envoy": ['.evy'],
"application/etl": ['.etl'],
"application/fractals": ['.fif'],
"application/fsharp-script": ['.fsscript', '.fsx'],
"application/futuresplash": ['.spl'],
"application/hta": ['.hta'],
"application/internet-property-stream": ['.acx'],
"application/java-archive": ['.jar'],
"application/json": ['.json'],
"application/liquidmotion": ['.jck', '.jcz'],
"application/mac-binhex40": ['.hqx'],
"application/ms-vsi": ['.vsi'],
"application/msaccess": ['.accdb', '.accde', '.accdt', '.ade', '.adp', '.mda', '.mde'],
"application/msaccess.addin": ['.accda'],
"application/msaccess.cab": ['.accdc'],
"application/msaccess.ftemplate": ['.accft'],
"application/msaccess.runtime": ['.accdr'],
"application/msaccess.webapplication": ['.accdw'],
"application/msword": ['.doc', '.dot', '.wbk', '.wiz'],
"application/octet-stream": ['.aaf', '.aca', '.afm', '.asd', '.asi', '.bin', '.cab', '.chm', '.cur', '.dat', '.deploy', '.dsp', '.dwp', '.emz', '.eot', '.exe', '.fla', '.hhk', '.hhp', '.hxd', '.hxh', '.hxi', '.hxq', '.hxr', '.hxs', '.hxw', '.ics', '.inf', '.java', '.jpb', '.lpk', '.lzh', '.mdp', '.mix', '.msi', '.mso', '.ocx', '.pcx', '.pcz', '.pfb', '.pfm', '.prm', '.prx', '.psd', '.psm', '.psp', '.qxd', '.rar', '.sea', '.smi', '.snp', '.thn', '.toc', '.ttf', '.u32', '.xsn', '.xtp'],
"application/oda": ['.oda'],
"application/oleobject": ['.ods'],
"application/olescript": ['.axs'],
"application/onenote": ['.one', '.onea', '.onepkg', '.onetmp', '.onetoc', '.onetoc2'],
"application/opensearchdescription+xml": ['.osdx'],
"application/pdf": ['.pdf'],
"application/pics-rules": ['.prf'],
"application/pkcs10": ['.p10'],
"application/pkcs7-mime": ['.p7c', '.p7m'],
"application/pkcs7-signature": ['.p7s'],
"application/pkix-crl": ['.crl'],
"application/postscript": ['.ai', '.eps', '.ps'],
"application/rat-file": ['.rat'],
"application/rtf": ['.rtf'],
"application/sdp": ['.sdp'],
"application/set-payment-initiation": ['.setpay'],
"application/set-registration-initiation": ['.setreg'],
"application/streamingmedia": ['.ssm'],
"application/vnd.adobe.air-application-installer-package+zip": ['.air'],
"application/vnd.fdf": ['.fdf'],
"application/vnd.ms-excel": ['.slk', '.xla', '.xlc', '.xld', '.xlk', '.xll', '.xlm', '.xls', '.xlt', '.xlw'],
"application/vnd.ms-excel.addin.macroEnabled.12": ['.xlam'],
"application/vnd.ms-excel.sheet.binary.macroEnabled.12": ['.xlsb'],
"application/vnd.ms-excel.sheet.macroEnabled.12": ['.xlsm'],
"application/vnd.ms-excel.template.macroEnabled.12": ['.xltm'],
"application/vnd.ms-mediapackage": ['.mpf'],
"application/vnd.ms-office.calx": ['.calx'],
"application/vnd.ms-officetheme": ['.thmx'],
"application/vnd.ms-pki.certstore": ['.sst'],
"application/vnd.ms-pki.pko": ['.pko'],
"application/vnd.ms-pki.seccat": ['.cat'],
"application/vnd.ms-pki.stl": ['.stl'],
"application/vnd.ms-powerpoint": ['.pot', '.ppa', '.pps', '.ppt', '.pwz'],
"application/vnd.ms-powerpoint.addin.macroEnabled.12": ['.ppam'],
"application/vnd.ms-powerpoint.presentation.macroEnabled.12": ['.pptm'],
"application/vnd.ms-powerpoint.slide.macroEnabled.12": ['.sldm'],
"application/vnd.ms-powerpoint.slideshow.macroEnabled.12": ['.ppsm'],
"application/vnd.ms-powerpoint.template.macroEnabled.12": ['.potm'],
"application/vnd.ms-project": ['.mpp'],
"application/vnd.ms-visio.viewer": ['.vdx'],
"application/vnd.ms-word.document.macroEnabled.12": ['.docm'],
"application/vnd.ms-word.template.macroEnabled.12": ['.dotm'],
"application/vnd.ms-works": ['.wcm', '.wdb', '.wks', '.wps'],
"application/vnd.ms-wpl": ['.wpl'],
"application/vnd.ms-xpsdocument": ['.xps'],
"application/vnd.oasis.opendocument.presentation": ['.odp'],
"application/vnd.oasis.opendocument.text": ['.odt'],
"application/vnd.openxmlformats-officedocument.presentationml.presentation": ['.pptx'],
"application/vnd.openxmlformats-officedocument.presentationml.slide": ['.sldx'],
"application/vnd.openxmlformats-officedocument.presentationml.slideshow": ['.ppsx'],
"application/vnd.openxmlformats-officedocument.presentationml.template": ['.potx'],
"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": ['.xlsx'],
"application/vnd.openxmlformats-officedocument.spreadsheetml.template": ['.xltx'],
"application/vnd.openxmlformats-officedocument.wordprocessingml.document": ['.docx'],
"application/vnd.openxmlformats-officedocument.wordprocessingml.template": ['.dotx'],
"application/vnd.rn-realmedia": ['.rm'],
"application/vnd.rn-rn_music_package": ['.rmp'],
"application/vnd.visio": ['.vsd', '.vss', '.vst', '.vsw', '.vsx', '.vtx'],
"application/vnd.wap.wmlc": ['.wmlc'],
"application/vnd.wap.wmlscriptc": ['.wmlsc'],
"application/vsix": ['.vsix'],
"application/windows-library+xml": ['.library-ms'],
"application/windows-search-connector+xml": ['.searchConnector-ms'],
"application/winhlp": ['.hlp'],
"application/wlmoviemaker": ['.WLMP'],
"application/x-7z-compressed": ['.7z'],
"application/x-bcpio": ['.bcpio'],
"application/x-bridge-url": ['.adobebridge'],
"application/x-cdf": ['.cdf'],
"application/x-compress": ['.z'],
"application/x-compressed": ['.tgz'],
"application/x-cpio": ['.cpio'],
"application/x-csh": ['.csh'],
"application/x-director": ['.dcr', '.dir', '.dxr'],
"application/x-dvi": ['.dvi'],
"application/x-gtar": ['.gtar'],
"application/x-gzip": ['.gz'],
"application/x-hdf": ['.hdf'],
"application/x-internet-signup": ['.ins', '.isp'],
"application/x-iphone": ['.iii'],
"application/x-itunes-ipa": ['.ipa'],
"application/x-itunes-ipg": ['.ipg'],
"application/x-itunes-ipsw": ['.ipsw'],
"application/x-itunes-ite": ['.ite'],
"application/x-itunes-itlp": ['.itlp'],
"application/x-itunes-itms": ['.itms'],
"application/x-itunes-itpc": ['.itpc'],
"application/x-java-applet": ['.class'],
"application/x-java-jnlp-file": ['.jnlp'],
"application/x-javascript": ['.js'],
"application/x-latex": ['.latex'],
"application/x-miva-compiled": ['.mvc'],
"application/x-mmxp": ['.mxp'],
"application/x-mpeg": ['.amc'],
"application/x-ms-application": ['.application'],
"application/x-ms-license": ['.slupkg-ms'],
"application/x-ms-manifest": ['.manifest'],
"application/x-ms-reader": ['.lit'],
"application/x-ms-vsto": ['.vsto'],
"application/x-ms-wmd": ['.wmd'],
"application/x-ms-wmz": ['.wmz'],
"application/x-ms-xbap": ['.xbap'],
"application/x-msaccess": ['.mdb'],
"application/x-mscardfile": ['.crd'],
"application/x-msclip": ['.clp'],
"application/x-msdownload": ['.dll'],
"application/x-msmediaview": ['.m13', '.m14', '.mvb'],
"application/x-msmetafile": ['.wmf'],
"application/x-msmoney": ['.mny'],
"application/x-mspublisher": ['.pub'],
"application/x-msschedule": ['.scd'],
"application/x-msterminal": ['.trm'],
"application/x-mswrite": ['.wri'],
"application/x-netcdf": ['.nc'],
"application/x-oleobject": ['.hhc'],
"application/x-perfmon": ['.pma', '.pmc', '.pml', '.pmr', '.pmw'],
"application/x-pkcs12": ['.p12', '.pfx'],
"application/x-pkcs7-certificates": ['.p7b', '.spc'],
"application/x-pkcs7-certreqresp": ['.p7r'],
"application/x-podcast": ['.pcast'],
"application/x-quicktimeplayer": ['.qtl'],
"application/x-safari-safariextz": ['.safariextz'],
"application/x-safari-webarchive": ['.webarchive'],
"application/x-sgimb": ['.sgimb'],
"application/x-sh": ['.sh'],
"application/x-shar": ['.shar'],
"application/x-shockwave-flash": ['.mfp', '.swf'],
"application/x-silverlight-app": ['.xap'],
"application/x-smaf": ['.mmf'],
"application/x-stuffit": ['.sit'],
"application/x-sv4cpio": ['.sv4cpio'],
"application/x-sv4crc": ['.sv4crc'],
"application/x-tar": ['.tar'],
"application/x-tcl": ['.tcl'],
"application/x-tex": ['.tex'],
"application/x-texinfo": ['.texi', '.texinfo'],
"application/x-troff": ['.roff', '.t', '.tr'],
"application/x-troff-man": ['.man'],
"application/x-troff-me": ['.me'],
"application/x-troff-ms": ['.ms'],
"application/x-ustar": ['.ustar'],
"application/x-wais-source": ['.src'],
"application/x-wlpg-detect": ['.wlpginstall'],
"application/x-wlpg3-detect": ['.wlpginstall3'],
"application/x-x509-ca-cert": ['.cer', '.crt', '.der'],
"application/x-zip-compressed": ['.zip'],
"application/xaml+xml": ['.xaml'],
"application/xhtml+xml": ['.xht', '.xhtml'],
"application/xml": ['.asa', '.asax', '.ascx', '.ashx', '.asmx', '.aspx', '.config', '.coverage', '.datasource', '.dgml', '.generictest', '.hxa', '.hxc', '.hxe', '.hxf', '.hxk', '.hxv', '.loadtest', '.master', '.mtx', '.orderedtest', '.psess', '.rdlc', '.resx', '.ruleset', '.settings', '.sitemap', '.skin', '.snippet', '.svc', '.testrunconfig', '.testsettings', '.trx', '.vscontent', '.vsmdi', '.webtest', '.wiq', '.xmta', '.xsc', '.xss'],
"audio/aac": ['.AAC', '.ADTS'],
"audio/ac3": ['.ac3'],
"audio/aiff": ['.aifc', '.aiff', '.cdda'],
"audio/audible": ['.aa'],
"audio/basic": ['.au', '.snd'],
"audio/m4a": ['.m4a'],
"audio/m4b": ['.m4b'],
"audio/m4p": ['.m4p'],
"audio/mid": ['.mid', '.midi', '.rmi'],
"audio/mpeg": ['.mp3'],
"audio/scpls": ['.pls'],
"audio/vnd.audible.aax": ['.aax'],
"audio/vnd.dlna.adts": ['.ADT'],
"audio/wav": ['.wav', '.wave'],
"audio/x-aiff": ['.aif'],
"audio/x-caf": ['.caf'],
"audio/x-gsm": ['.gsm'],
"audio/x-m4r": ['.m4r'],
"audio/x-mpegurl": ['.m3u', '.m3u8'],
"audio/x-ms-wax": ['.wax'],
"audio/x-ms-wma": ['.wma'],
"audio/x-pn-realaudio": ['.ra', '.ram'],
"audio/x-pn-realaudio-plugin": ['.rpm'],
"audio/x-sd2": ['.sd2'],
"audio/x-smd": ['.smd', '.smx', '.smz'],
"drawing/x-dwf": ['.dwf'],
"image/bmp": ['.bmp', '.dib'],
"image/cis-cod": ['.cod'],
"image/gif": ['.gif'],
"image/ief": ['.ief'],
"image/jpeg": ['.jpeg', '.jpe', '.jpg'],
"image/pict": ['.pct', '.pic', '.pict'],
"image/pjpeg": ['.jfif'],
"image/png": ['.png', '.pnz'],
"image/tiff": ['.tif', '.tiff'],
"image/vnd.ms-photo": ['.wdp'],
"image/vnd.rn-realflash": ['.rf'],
"image/vnd.wap.wbmp": ['.wbmp'],
"image/x-cmu-raster": ['.ras'],
"image/x-cmx": ['.cmx'],
"image/x-icon": ['.ico'],
"image/x-jg": ['.art'],
"image/x-macpaint": ['.mac', '.pnt', '.pntg'],
"image/x-portable-anymap": ['.pnm'],
"image/x-portable-bitmap": ['.pbm'],
"image/x-portable-graymap": ['.pgm'],
"image/x-portable-pixmap": ['.ppm'],
"image/x-quicktime": ['.qti', '.qtif'],
"image/x-rgb": ['.rgb'],
"image/x-xbitmap": ['.xbm'],
"image/x-xpixmap": ['.xpm'],
"image/x-xwindowdump": ['.xwd'],
"message/rfc822": ['.eml', '.mht', '.mhtml', '.nws'],
"text/css": ['.css'],
"text/csv": ['.csv'],
"text/dlm": ['.dlm'],
"text/h323": ['.323'],
"text/html": ['.htm', '.html', '.hxt', '.shtml'],
"text/iuls": ['.uls'],
"text/jscript": ['.jsx'],
"text/plain": ['.XOML', '.asm', '.bas', '.c', '.cc', '.cd', '.cnf', '.cpp', '.cs', '.csdproj', '.csproj', '.cxx', '.dbproj', '.def', '.dsw', '.h', '.hpp', '.hxx', '.i', '.idl', '.inc', '.inl', '.ipproj', '.jsxbin', '.lst', '.mak', '.map', '.mk', '.odh', '.odl', '.pkgdef', '.pkgundef', '.rc', '.rc2', '.rct', '.rgs', '.s', '.sln', '.sol', '.sor', '.srf', '.tlh', '.tli', '.txt', '.user', '.vb', '.vbdproj', '.vbproj', '.vcs', '.vddproj', '.vdp', '.vdproj', '.vspscc', '.vsscc', '.vssscc', '.xdr'],
"text/richtext": ['.rtx'],
"text/scriptlet": ['.sct', '.wsc'],
"text/sgml": ['.sgml'],
"text/tab-separated-values": ['.tsv'],
"text/vbscript": ['.vbs'],
"text/vnd.wap.wml": ['.wml'],
"text/vnd.wap.wmlscript": ['.wmls'],
"text/webviewhtml": ['.htt'],
"text/x-component": ['.htc'],
"text/x-hdml": ['.hdml'],
"text/x-html-insertion": ['.qht', '.qhtm'],
"text/x-ms-contact": ['.contact'],
"text/x-ms-group": ['.group'],
"text/x-ms-iqy": ['.iqy'],
"text/x-ms-odc": ['.odc'],
"text/x-ms-rqy": ['.rqy'],
"text/x-setext": ['.etx'],
"text/x-vcard": ['.vcf'],
"text/xml": ['.xml', '.AddIn', '.SSISDeploymentManifest', '.disco', '.dll.config', '.dtd', '.dtsConfig', '.exe.config', '.mno', '.vml', '.vsct', '.vsixlangpack', '.vsixmanifest', '.vssettings', '.vstemplate', '.wsdl', '.xml', '.xrm-ms', '.xsd', '.xsf', '.xsl', '.xslt'],
"video/3gpp": ['.3gp', '.3gpp'],
"video/3gpp2": ['.3g2', '.3gp2'],
"video/mp4": ['.mp4', '.mp4v'],
"video/mpeg": ['.mpeg', '.m1v', '.m2v', '.mod', '.mp2', '.mp2v', '.mpa', '.mpe', '.mpeg', '.mpg', '.mpv2', '.vbk'],
"video/quicktime": ['.mov', '.mqv', '.qt'],
"video/vnd.dlna.mpeg-tts": ['.m2t', '.m2ts', '.mts', '.ts', '.tts'],
"video/x-dv": ['.dif', '.dv'],
"video/x-flv": ['.flv'],
"video/x-ivf": ['.IVF'],
"video/x-la-asf": ['.lsf', '.lsx'],
"video/x-m4v": ['.m4v'],
"video/x-ms-asf": ['.asf', '.asr', '.asx', '.nsc'],
"video/x-ms-wm": ['.wm'],
"video/x-ms-wmp": ['.wmp'],
"video/x-ms-wmv": ['.wmv'],
"video/x-ms-wmx": ['.wmx'],
"video/x-ms-wvx": ['.wvx'],
"video/x-msvideo": ['.avi'],
"video/x-sgi-movie": ['.movie'],
"x-world/x-vrml": ['.flr', '.wrl', '.wrz', '.xaf', '.xof']
}